version: "3.8"

networks:
  sellTech:
    driver: bridge

services:
  app:
    build:
      args:
        user: dummy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sellTech

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --init-file /data/application/init.sql
    volumes:
      - ./docker-compose/mysql/init_db.sql:/data/application/init.sql
    networks:
      - sellTech

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - sellTech
